import { createElement } from 'lwc';
import Hotel_Object_LWC_Components from 'c/hotel_Object_LWC_Components';

describe('c-hotel-object-l-w-c-components', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-hotel-object-l-w-c-components', {
            is: Hotel_Object_LWC_Components
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});